framework:
    secret: '%env(APP_SECRET)%'
    session:
        cookie_secure: auto
    # ... other framework configuration ...
    
when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
