nelmio_cors:
    defaults:
        allow_origin: ['https://stack-shelf-react-d0c9679401c9.herokuapp.com', 'http://localhost:5173']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['https://stack-shelf-react-d0c9679401c9.herokuapp.com', 'http://localhost:5173']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600
